package com.rechenggit.core.dal.mapper;

import com.rechenggit.core.dal.dataobject.Sequence;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SequenceMapper {
    List<Sequence> loadAll();

    Sequence lock(String sequenceName);

    void update(@Param("sequenceName") String sequenceName,@Param("beforeValue") Long beforeValue,@Param("afterValue") Long afterValue);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    int updateByPrimaryKey(Sequence record);
}