package com.rechenggit.core.dal.mapper;

import com.rechenggit.core.dal.dataobject.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    Member selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_member
     *
     * @mbggenerated Wed Sep 05 15:25:34 CST 2018
     */
    int updateByPrimaryKey(Member record);
}