package com.rechenggit.core.dal.dataobject;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.MEMBER_ID
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.MEMBER_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.MEMBER_SHORT_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String memberShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.MEMBER_TYPE
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Integer memberType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.LOCK_STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Integer lockStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.FROM_IP
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.ACTIVE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Date activeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.CREATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.CREATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.UPDATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.MEMO
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_member.SECURITY_LEVEL
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    private String securityLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.MEMBER_ID
     *
     * @return the value of tm_member.MEMBER_ID
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.MEMBER_ID
     *
     * @param memberId the value for tm_member.MEMBER_ID
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.MEMBER_NAME
     *
     * @return the value of tm_member.MEMBER_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.MEMBER_NAME
     *
     * @param memberName the value for tm_member.MEMBER_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.MEMBER_SHORT_NAME
     *
     * @return the value of tm_member.MEMBER_SHORT_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getMemberShortName() {
        return memberShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.MEMBER_SHORT_NAME
     *
     * @param memberShortName the value for tm_member.MEMBER_SHORT_NAME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setMemberShortName(String memberShortName) {
        this.memberShortName = memberShortName == null ? null : memberShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.MEMBER_TYPE
     *
     * @return the value of tm_member.MEMBER_TYPE
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Integer getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.MEMBER_TYPE
     *
     * @param memberType the value for tm_member.MEMBER_TYPE
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setMemberType(Integer memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.STATUS
     *
     * @return the value of tm_member.STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.STATUS
     *
     * @param status the value for tm_member.STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.LOCK_STATUS
     *
     * @return the value of tm_member.LOCK_STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Integer getLockStatus() {
        return lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.LOCK_STATUS
     *
     * @param lockStatus the value for tm_member.LOCK_STATUS
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setLockStatus(Integer lockStatus) {
        this.lockStatus = lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.FROM_IP
     *
     * @return the value of tm_member.FROM_IP
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.FROM_IP
     *
     * @param fromIp the value for tm_member.FROM_IP
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.ACTIVE_TIME
     *
     * @return the value of tm_member.ACTIVE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.ACTIVE_TIME
     *
     * @param activeTime the value for tm_member.ACTIVE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.CREATE_TIME
     *
     * @return the value of tm_member.CREATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.CREATE_TIME
     *
     * @param createTime the value for tm_member.CREATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.UPDATE_TIME
     *
     * @return the value of tm_member.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.UPDATE_TIME
     *
     * @param updateTime the value for tm_member.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.CREATE_USER
     *
     * @return the value of tm_member.CREATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.CREATE_USER
     *
     * @param createUser the value for tm_member.CREATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.UPDATE_USER
     *
     * @return the value of tm_member.UPDATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.UPDATE_USER
     *
     * @param updateUser the value for tm_member.UPDATE_USER
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.MEMO
     *
     * @return the value of tm_member.MEMO
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.MEMO
     *
     * @param memo the value for tm_member.MEMO
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_member.SECURITY_LEVEL
     *
     * @return the value of tm_member.SECURITY_LEVEL
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public String getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_member.SECURITY_LEVEL
     *
     * @param securityLevel the value for tm_member.SECURITY_LEVEL
     *
     * @mbggenerated Fri Sep 07 14:34:11 CST 2018
     */
    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel == null ? null : securityLevel.trim();
    }
}