package com.rechenggit.core.dal.dataobject;

public class Sequence {
    /**
     * 序列名
     */
    private String  name;
    /**
     * 当前值
     */
    private Long    currentValue;
    /**
     * 增量
     */
    private Integer increment;
    /**
     * 单次取值数量
     */
    private Integer total;
    /**
     * 刷新阀值
     */
    private Integer threshold;
    /**
     * 刷新后值
     */
    private Long    afterValue;
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.NAME
     *
     * @param name the value for t_sequence.NAME
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.CURRENT_VALUE
     *
     * @return the value of t_sequence.CURRENT_VALUE
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public Long getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.CURRENT_VALUE
     *
     * @param currentValue the value for t_sequence.CURRENT_VALUE
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public void setCurrentValue(Long currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.INCREMENT
     *
     * @return the value of t_sequence.INCREMENT
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.INCREMENT
     *
     * @param increment the value for t_sequence.INCREMENT
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.TOTAL
     *
     * @return the value of t_sequence.TOTAL
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.TOTAL
     *
     * @param total the value for t_sequence.TOTAL
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sequence.THRESHOLD
     *
     * @return the value of t_sequence.THRESHOLD
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sequence.THRESHOLD
     *
     * @param threshold the value for t_sequence.THRESHOLD
     *
     * @mbggenerated Thu Sep 06 15:36:31 CST 2018
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    public Long getAfterValue() {
        return afterValue;
    }

    public void setAfterValue(Long afterValue) {
        this.afterValue = afterValue;
    }
}