package com.rechenggit.core.dal.dataobject;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.store_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.member_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.store_name
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.address
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.suburb
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String suburb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.state
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.post_code
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.contact_number
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String contactNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_store.email
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.store_id
     *
     * @return the value of tm_store.store_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.store_id
     *
     * @param storeId the value for tm_store.store_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.member_id
     *
     * @return the value of tm_store.member_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.member_id
     *
     * @param memberId the value for tm_store.member_id
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.store_name
     *
     * @return the value of tm_store.store_name
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.store_name
     *
     * @param storeName the value for tm_store.store_name
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.address
     *
     * @return the value of tm_store.address
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.address
     *
     * @param address the value for tm_store.address
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.suburb
     *
     * @return the value of tm_store.suburb
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getSuburb() {
        return suburb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.suburb
     *
     * @param suburb the value for tm_store.suburb
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setSuburb(String suburb) {
        this.suburb = suburb == null ? null : suburb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.state
     *
     * @return the value of tm_store.state
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.state
     *
     * @param state the value for tm_store.state
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.post_code
     *
     * @return the value of tm_store.post_code
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.post_code
     *
     * @param postCode the value for tm_store.post_code
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.contact_number
     *
     * @return the value of tm_store.contact_number
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.contact_number
     *
     * @param contactNumber the value for tm_store.contact_number
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_store.email
     *
     * @return the value of tm_store.email
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_store.email
     *
     * @param email the value for tm_store.email
     *
     * @mbggenerated Fri Sep 07 14:27:06 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}